name: Publish to GitHub Packages

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
      
      - name: Publish package
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_VERSION: ${{ github.ref_name }}
